version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672" # rabbit mq port
      - "15672:15672" # manage prot
    environment:
      - RABBITMQ_DEFAULT_USER=admin # 기본사용자 이름
      - RABBITMQ_DEFAULT_PASS=admin # 기본사용자 비밀번호